attributes:
  tunnel_type:
    type: "select"
    weight: 10
    value: "gre"
    label: "Tunnel Type"
    description: "Choose which technology MidoNet will use to encapsulate data between hosts"
    values:
      - data: "gre"
        label: "GRE tunnels"
      - data: "vxlan"
        label: "VXLAN tunnels"
  version:
    type: "select"
    weight: 20
    value: "v2015.01"
    label: "MidoNet version"
    description: "Choose which version of MidoNet you want to deploy"
    values:
      - data: "v2015.01"
        label: "v2015.01"
      - data: "v2015.03"
        label: "v2015.03"
